# Generated by Django 3.2.6 on 2021-08-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
